#!/bin/bash

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
declare -A TARGET_TAGS=([distcc-tcp]="latest,latest-tcp,tcp" [distcc-ssh]="latest-ssh,ssh")
for target in "${!TARGET_TAGS[@]}"; do
    IFS=',' read -ra tags <<< "${TARGET_TAGS[${target}]}"
    docker build "--build-arg=BUILD_DATE=${BUILD_DATE}" \
                 "--build-arg=VCS_REF=${SOURCE_COMMIT}" \
                 "${tags[@]/#/--tag=${DOCKER_REPO}:}" \
                 "--target=${target}" \
                 .
done
